format = """
[ ](bold lavender)$os$hostname\
[](bold lavender)$username\
[](bold lavender)$directory\
[](bold lavender)$c$java$kotlin$lua$nodejs$php$python\
[](bold lavender)$docker_context$kubernetes\
[](bold lavender)$time\
[ ](bold lavender)$line_break$character"""

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "sky"

[os.symbols]
Arch = " 󰣇 - Arch Linux "

[username]
show_always = true
style_user = "teal"
style_root = "rosewater"
format = '[ $user ]($style)'

[directory]
style = "maroon"
format = "[  $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

[c]
symbol = " "
style = "peach"
format = '[[   $symbol( $version) ](flamingo)]($style)'

[java]
symbol = " "
style = "peach"
format = '[[   $symbol( $version) ](flamingo)]($style)'

[kotlin]
symbol = " "
style = "peach"
format = '[[   $symbol( $version) ](flamingo)]($style)'

[lua]
symbol = " "
style = "peach"
format = '[[   $symbol( $version) ](flamingo)]($style)'

[nodejs]
symbol = " "
style = "peach"
format = '[[   $symbol( $version) ](flamingo)]($style)'

[php]
symbol = " "
style = "peach"
format = '[[   $symbol( $version) ](flamingo)]($style)'

[python]
symbol = " "
style = "peach"
format = '[[   $symbol( $version) ](flamingo)]($style)'

[docker_context]
symbol = " "
style = "peach"
format = '[[  $symbol( $context) ](flamingo)]($style)'

[kubernetes]
symbol = "󱃾 "
style = "peach"
format = '[[  $symbol( $context) ](flamingo)]($style)'

[time]
disabled = false
time_format = "%R"
style = "sapphire"
format = '[[  $time ](mauve)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'
vimcmd_symbol = '[](bold green)'
vimcmd_replace_one_symbol = '[](bold purple)'
vimcmd_replace_symbol = '[](bold purple)'
vimcmd_visual_symbol = '[](bold yellow)'
